# Generated by Django 2.2.1 on 2020-03-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('link', models.TextField()),
                ('prev_score', models.IntegerField()),
                ('round_number', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
