# Generated by Django 3.0.4 on 2020-03-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeteam',
            name='score',
            field=models.IntegerField(),
        ),
    ]
